const API = '/api/rooms';
const app = document.getElementById('app');
const themes = {
  'Космос': ['Тема космос Арт1.png', 'Тема космос Арт2.png', 'Тема космос Арт3.png'],
  'Морские приключения': ['Тема морские приключения Арт1.png', 'Тема морские приключения Арт2.png', 'Тема морские приключения Арт3.png'],
  'Путешествия': ['Тема путешествия Арт1.png', 'Тема путешествия Арт2.png', 'Тема путешествия Арт3.png'],
};
let state = { role: '', roomCode: '', name: '', room: null, upload: null };
const req = (url, opt={}) => fetch(url, { headers: { 'Content-Type': 'application/json' }, ...opt }).then(r=>r.json());

function home(){ app.innerHTML = `<div class='card'><div class='title'>Арт игра</div><div class='row'><button id='adult'>Учитель</button><button class='secondary' id='child'>Ребенок</button></div></div>`; adult.onclick=adultSetup; child.onclick=childSetup; }
function adultSetup(){ app.innerHTML=`<div class='card'><div class='title'>Комната</div><div class='row'><button id='single'>Один</button><button id='multi'>Несколько</button></div><div style='margin-top:10px'><select id='theme'>${Object.keys(themes).map(t=>`<option>${t}</option>`).join('')}</select></div><div style='margin-top:10px'><button id='create'>Создать</button></div></div>`; single.classList.add('active'); single.onclick=()=>{single.classList.add('active');multi.classList.remove('active')}; multi.onclick=()=>{multi.classList.add('active');single.classList.remove('active')}; create.onclick=async()=>{const t=theme.value; const mode=multi.classList.contains('active')?'multi':'single'; const chosen=themes[t][Math.floor(Math.random()*themes[t].length)]; const data=await req(API,{method:'POST',body:JSON.stringify({mode,theme:t,chosen})}); state={...state, role:'adult', roomCode:data.room.code, room:data.room}; adultLobby();}; }
function childSetup(){ app.innerHTML=`<div class='card'><div class='title'>Вход</div><input id='name' placeholder='Имя Фамилия'><div style='height:8px'></div><input id='code' placeholder='Код комнаты'><div style='height:10px'></div><button id='join'>Войти</button></div>`; join.onclick=async()=>{state.name=name.value.trim(); state.roomCode=code.value.trim(); if(!state.name||!state.roomCode) return; const r=await req(`${API}/${state.roomCode}/join`,{method:'POST',body:JSON.stringify({name:state.name})}); if(!r.ok)return; state.role='child'; state.room=r.room; tick(); renderByStage();}; }

async function fetchRoom(){ const r=await req(`${API}/${state.roomCode}`); if(r.ok) state.room=r.room; }
function adultLobby(){ app.innerHTML=`<div class='grid'><div class='card'><div class='title'>Дети</div><div id='kids'></div></div><div class='card right'><div class='title'>Код</div><div class='badge' style='font-size:30px'>${state.roomCode}</div><div style='margin-top:10px'><button id='start'>Старт</button></div></div></div>`; renderKids(); start.onclick=()=>goStage('memorize'); tick(); }
function renderKids(){ kids.innerHTML=state.room.kids.map(k=>`<div class='player'>${k.name}<button class='secondary' data-name='${encodeURIComponent(k.name)}'>✕</button></div>`).join('')||'Пусто'; kids.querySelectorAll('button').forEach(b=>b.onclick=async()=>{await fetch(`${API}/${state.roomCode}/kid/${b.dataset.name}`,{method:'DELETE'}); await fetchRoom(); renderKids();}); }
async function goStage(stage){ await req(`${API}/${state.roomCode}/stage`,{method:'POST',body:JSON.stringify({stage})}); await fetchRoom(); renderByStage(); }
function leftMs(){ const d=state.room.stage==='memorize'?120000:300000; return Math.max(0,d-(Date.now()-state.room.stageStartedAt)); }

function renderByStage(){ if(state.role==='adult'&&state.room.stage==='lobby') return adultLobby(); if(state.room.stage==='memorize') return memorize(); if(state.room.stage==='draw') return draw(); if(state.room.stage==='vote') return vote(); if(state.room.stage==='result') return result(); }
function memorize(){ app.innerHTML=`<div class='card'><div class='title'>Запомни</div><div id='timer' class='badge'></div><div class='imgbox'><img src='${state.room.chosen}'></div></div>`; timerRun(()=>{if(leftMs()===0 && state.role==='adult') goStage('draw');},()=>`${Math.ceil(leftMs()/1000)} сек`); }
function draw(){ app.innerHTML=`<div class='card'><div class='title'>Рисование</div><div id='timer' class='badge'></div><div class='toolbar'><input id='size' type='range' min='2' max='24' value='5' style='width:120px'><button class='secondary' id='clear'>Очистить</button><label class='secondary' style='display:inline-block;padding:12px 14px;cursor:pointer'>Загрузить<input id='upload' type='file' accept='image/*' class='hidden'></label></div><canvas id='canvas' width='900' height='470'></canvas><div><button id='done'>Готово</button></div></div>`; paint(); done.onclick=finishArt; timerRun(()=>{if(leftMs()===0 && state.role==='adult') finishStageAdult();},()=>`${Math.ceil(leftMs()/1000)} сек`); }
async function finishArt(){ const c=document.getElementById('canvas'); const art=c?c.toDataURL('image/png'):null; if(state.role==='child') await req(`${API}/${state.roomCode}/art`,{method:'POST',body:JSON.stringify({name:state.name,art,upload:state.upload})}); if(state.role==='adult') await finishStageAdult(); }
async function finishStageAdult(){ if(state.room.mode==='multi') await goStage('vote'); else { await req(`${API}/${state.roomCode}/stage`,{method:'POST',body:JSON.stringify({stage:'result'})}); await fetchRoom(); renderByStage(); } }
function vote(){ if(state.role==='adult'){ app.innerHTML=`<div class='card'><div class='title'>Голосование</div><button id='final'>Показать итог</button></div>`; final.onclick=async()=>{await req(`${API}/${state.roomCode}/results`,{method:'POST'}); await fetchRoom(); renderByStage();}; return; } app.innerHTML=`<div class='card'><div class='title'>Выбери лучший</div><div class='gallery'>${state.room.kids.map(k=>`<div class='vote-card'><img src='${k.art||k.upload||state.room.chosen}'><button data-name='${k.name}'>Голос</button></div>`).join('')}</div></div>`; app.querySelectorAll('button').forEach(b=>b.onclick=async()=>{await req(`${API}/${state.roomCode}/vote`,{method:'POST',body:JSON.stringify({voter:state.name,target:b.dataset.name})}); app.innerHTML=`<div class='card'><div class='title'>Принято</div></div>`;}); }
function result(){ if(state.room.mode==='single'){ const k=state.room.kids[0]||{name:'Ребенок'}; app.innerHTML=`<div class='card'><div class='title'>Отлично, ${k.name}!</div><div class='grid'><img src='${state.room.chosen}'><img src='${k.art||k.upload||state.room.chosen}'></div></div>`; return;} req(`${API}/${state.roomCode}`).then(r=>{const arr=(r.room.results||[]); app.innerHTML=`<div class='card'><div class='title'>Победители</div><img src='Экран победителей.png' style='width:100%;max-height:280px;object-fit:contain'><div class='player'>1 <b>${arr[0]?.name||'-'}</b></div><div class='player'>2 <b>${arr[1]?.name||'-'}</b></div><div class='player'>3 <b>${arr[2]?.name||'-'}</b></div></div>`;}); }
function paint(){ const canvas=document.getElementById('canvas'); const ctx=canvas.getContext('2d'); ctx.lineCap='round'; let d=false,p='#1a2440'; const cs=['#1a2440','#ff5f5f','#ffc93d','#4cc9f0','#2ec27e','#8e69ff']; const bar=document.createElement('div'); bar.className='toolbar'; bar.innerHTML=cs.map((c,i)=>`<div class='swatch ${i===0?'active':''}' data-c='${c}' style='background:${c}'></div>`).join(''); canvas.parentElement.insertBefore(bar,canvas); bar.querySelectorAll('.swatch').forEach(s=>s.onclick=()=>{bar.querySelectorAll('.swatch').forEach(x=>x.classList.remove('active'));s.classList.add('active');p=s.dataset.c;}); const pos=e=>{const r=canvas.getBoundingClientRect(); const t=e.touches?e.touches[0]:e; return{x:(t.clientX-r.left)*(canvas.width/r.width),y:(t.clientY-r.top)*(canvas.height/r.height)}}; const down=e=>{d=true;const q=pos(e);ctx.beginPath();ctx.moveTo(q.x,q.y)}; const move=e=>{if(!d)return;const q=pos(e);ctx.strokeStyle=p;ctx.lineWidth=size.value;ctx.lineTo(q.x,q.y);ctx.stroke()}; const up=()=>d=false; canvas.onmousedown=down;canvas.onmousemove=move;window.onmouseup=up;canvas.ontouchstart=down;canvas.ontouchmove=e=>{e.preventDefault();move(e)};canvas.ontouchend=up; clear.onclick=()=>ctx.clearRect(0,0,canvas.width,canvas.height); upload.onchange=e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader(); rd.onload=()=>state.upload=rd.result; rd.readAsDataURL(f)}; }
function timerRun(onEnd,text){ const i=setInterval(async()=>{timer.textContent=text(); await fetchRoom(); if(state.role==='adult'&&state.room.stage==='lobby') return; if((state.room.stage==='memorize'||state.room.stage==='draw') && leftMs()===0) onEnd(); if(!document.getElementById('timer')) clearInterval(i); if(state.room.stage!=='memorize'&&state.room.stage!=='draw') {clearInterval(i); renderByStage();}},1000); }
function tick(){ setInterval(async()=>{if(!state.roomCode)return; await fetchRoom(); if(state.role==='adult'&&state.room.stage==='lobby'&&document.getElementById('kids')) renderKids(); if(state.role==='child') renderByStage(); },2000); }
home();
